### ISSUE TITLE
Multiple LICENSE files present in some jars

### ISSUE THREAD

**Issue by zabetak** [apache/incubator-xtable#701]
### Search before asking

- [x] I had searched in the [issues](https://github.com/apache/incubator-xtable/issues?q=is%3Aissue) and found no similar issues.

### Please describe the bug 🐞

Some jars from those listed contain multiple LICENSE files, which are sometimes redundant and also create confusion.
```
xtable-api-0.3.0-incubating.jar
xtable-aws-0.3.0-incubating-bundled.jar
xtable-aws-0.3.0-incubating.jar
xtable-core_2.12-0.3.0-incubating.jar
xtable-hive-metastore-0.3.0-incubating-bundled.jar
xtable-hive-metastore-0.3.0-incubating.jar
xtable-hudi-support-extensions_2.12-0.3.0-incubating-bundled.jar
xtable-hudi-support-extensions_2.12-0.3.0-incubating.jar
xtable-hudi-support-utils-0.3.0-incubating.jar 
```
I checked using the following command:
```
for i in `ls *jar`;do  echo $i; jar tf $i | grep LICENSE; done
```

One common problem in most jars is that they have the following structure:
```
META-INF/LICENSE
META-INF/LICENSE-bundled
META-INF/licenses/
```
The LICENSE-bundled and licenses directory are clearly redundant for non-bundled jars and the opposite holds for bundled jars. In all cases there should be only one `LICENSE` file directly under META-INF directory.

The most problematic of all is `xtable-hive-metastore-0.3.0-incubating-bundled.jar` which contains lots of licenses in non-canonical places making it very hard to review. As before there should be only one main license file (i.e., META-INF/LICENSE) that lists all 3rd party code and necessary licenses should be only under (i.e., META-INF/licenses/ directory).

### Are you willing to submit PR?

- [ ] I am willing to submit a PR!
- [ ] I am willing to submit a PR but need help getting started!

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by vinishjail97** [comment]
Based on vote thread from @jbonofre.  

```
- NOK: DISCLAIMER-WIP is here, but it would be great to list why it's
still WIP (for instance, "Contains code that may not be compatible
with the Apache License" or so). Else it should be DISCLAIMER.
- NOK: LICENSE is there in the source distribution, but it should
mention that xtable-core/src/main/java/org/apache/xtable/hudi/HudiInstantUtils.java
contains code directly copied from
org.apache.hudi.common.table.timeline.HoodieActiveTimeline
```
hudi is a top-level ASF project and this guidance from ASF team mentions it's not recommended to include these dependencies. @zabetak @jbonofre Is this okay? 
https://issues.apache.org/jira/browse/LEGAL-684


```
- NOK: xtable-aws bundle jar includes a LICENSE file but AWS SDK is
not documented here. NOTICE should also include AWS SDK NOTICE (as
it's ALv2 dep).
- NOK: xtable-hive-metastore jar includes a LICENSE file but Guava,
Avro, Scala, Caffeine, RoaringBitmap, HttpClient, RocksDB, HBase,
javassist are not listed (same for the NOTICE file).
- NOK: xtable-hudi-support extension jar includes a LICENSE but
Jackson, log4j, guava, scala, j2objc, iceberg, delta, spark-sql,
caffeine, RoaringBitmap are not listed (same for the NOTICE file).
```
I will put up a PR for these license updates.

**Comment by zabetak** [comment]
Regarding `HudiInstantUtils.java` I prefer to not include it as explained in LEGAL-684.

Regarding the missing licenses, I raised https://github.com/apache/incubator-xtable/issues/700. 

This issue is more about the redundant LICENSE files that are present in some jars notably the hive-metastore one.

**Comment by vinishjail97** [comment]
@zabetak @jbonofre I have pushed the PR to update license file contents. Based on the legal guidance, we don't want to bloat the NOTICE file with these contents is what I have understood. I have removed the references for dependent license files as it was not followed in other ASF projects.  

https://github.com/apache/incubator-xtable/pull/707

**Comment by zabetak** [comment]
Just to clarify a bit more the problem described here, I will use some concrete examples.

### xtable-aws-0.3.0-incubating.jar
**Actual structure**
```
META-INF/licenses/
META-INF/LICENSE
META-INF/LICENSE-bundled
META-INF/licenses/LICENSE-antlr4-runtime
META-INF/licenses/LICENSE-checker-qual
META-INF/licenses/LICENSE-glassfish-java-servlet-jsp
META-INF/licenses/LICENSE-javax-annotation-api
META-INF/licenses/LICENSE-paranamer
META-INF/licenses/LICENSE-slf4j-api
```

**Expected structure**
```
META-INF/LICENSE
```

### xtable-aws-0.3.0-incubating-bundled.jar
**Actual structure**
```
META-INF/LICENSE-bundled
META-INF/licenses/
META-INF/licenses/LICENSE-antlr4-runtime
META-INF/licenses/LICENSE-checker-qual
META-INF/licenses/LICENSE-glassfish-java-servlet-jsp
META-INF/licenses/LICENSE-javax-annotation-api
META-INF/licenses/LICENSE-paranamer
META-INF/licenses/LICENSE-slf4j-api
META-INF/LICENSE
```

**Expected structure**
```
META-INF/licenses/
META-INF/licenses/LICENSE-antlr4-runtime
META-INF/licenses/LICENSE-checker-qual
META-INF/licenses/LICENSE-glassfish-java-servlet-jsp
META-INF/licenses/LICENSE-javax-annotation-api
META-INF/licenses/LICENSE-paranamer
META-INF/licenses/LICENSE-slf4j-api
META-INF/licenses/LICENSE-thoughtworks
META-INF/licenses/LICENSE-protobuf
META-INF/licenses/LICENSE-jcodings
META-INF/licenses/LICENSE-joni
META-INF/licenses/LICENSE-jaxb-impl
META-INF/licenses/LICENSE-jamon
META-INF/licenses/LICENSE-javassist
META-INF/LICENSE <-- The content is that of LICENSE-bundled
```

Much more work is needed for `xtable-hive-metastore-0.3.0-incubating-bundled.jar` and maybe others.

**Comment by zabetak** [comment]
While checking the content of xtable-hive-metastore-0.4.0-incubating-bundled.jar I noticed that there are two directories with license contents:
```
./xtable-hive-metastore-0.4.0-incubating-bundled.jar_META-INF/license
./xtable-hive-metastore-0.4.0-incubating-bundled.jar_META-INF/licenses
```
The directories must be merged or if `license` is not relevant it should be removed.

**Comment by zabetak** [comment]
To some extend the issue is still present in 0.4.0 RC2 release. I inspected the `META-INF` directory inside `xtable-aws-0.4.0-incubating-bundled.jar` and I see that there are two identical license files:
```
$ diff META-INF/LICENSE META-INF/LICENSE-bundled | wc -l
0
```

**Comment by slachiewicz** [comment]
I went back to [licensing-howto](https://infra.apache.org/licensing-howto.html) to work out how much of this XTable actually has to carry, and the answer is less than any of the open PRs assume, mine included. Putting the reading here rather than in a PR, since it bears on #743, #875, #876 and #895 equally.

Three things policy says:

- **A bundled Apache-2.0 dependency needs no LICENSE entry at all** when the licence applies uniformly. Listing it is *"useful for completeness"*, not required. 715 of this reactor's 860 third-party artifacts are Apache-2.0 — under about 30 different spellings, which is its own problem.
- **NOTICE must carry nothing that is not legally required.** *"It is important to keep NOTICE as brief and simple as possible, as each addition places a burden on downstream consumers."* The current `NOTICE-bundled` files run from 248 to 1175 lines. This is the one place policy actively requires a change rather than permitting one.
- **For LICENSE, a pointer to the licence text within the distribution plus a short note is sufficient.** Inlining the full text is allowed but *"best reserved for short licenses"*. `META-INF/licenses/` is not mentioned by policy at all — it is a convention, so it is not something anyone needs to win an argument about.

What that leaves as genuinely required is about 30 licence texts across the released bundles, and a short pointer list. Not an inventory of everything bundled.

So the proposal in #898 is: generate the LICENSE from each module's own resolved dependencies, listing only the non-Apache-2.0 components; let `ApacheNoticeResourceTransformer` produce NOTICE; delete the generator, the coverage script and the six hand-maintained files. For `xtable-aws` the NOTICE comes out at 110 lines against 248 maintained by hand.

Two things I would rather have settled here than in a PR:

1. **`javolution`.** Its POM says BSD; the text bundled in its jar is MIT, carrying a 2017 copyright for a 2010 artifact. #898 records it as MIT per the bundled text, which is a statement about provenance rather than a conclusion. If someone knows which is right, that is worth fixing at the source.
2. **Which direction to take.** #895 fixes the hand-maintained model; #898 removes it. They are alternatives, not increments — both touch `generate_shaded_license_metadata.py` and `validate_shaded_license_coverage.sh` in incompatible ways. I am not asking for #898 over #895; I am asking that the direction gets decided before either merges, so the loser is not rebased onto a different world.

Two findings from #895 hold whichever way that goes: the `[772]` regeneration of the hive-metastore shade includes, and that `validate_shaded_license_coverage.sh` has been a no-op since June because it discovers modules with `rg`, which is absent on `ubuntu-latest`.

Separately, `xtable-utilities` is still excluded from the release, per the 2024 [DISCUSS] thread. Its bundle needs 33 further licence texts and I have deliberately left it out of scope; #896 tracks shrinking it first, which would make the licence question much smaller.

*This comment was created with AI assistance.*

**Comment by slachiewicz** [comment]
Four open PRs close this issue: #743, #876 (with #875 for `branch-0.4`), #895 and #898. They overlap and can't all land. Since #701 drew a binding -1 in the 0.4.0 RC1 vote, this sits on the release path and is worth settling before more review time goes into any of them.

As I read them: #876 enforces one `LICENSE` and one `NOTICE` per jar and is the narrowest fix for the RC objection. #895 adds the `META-INF/licenses/` coverage check and the Hive 3.1.3 whitelist. #898 replaces the hand-maintained bundled files with generated ones. The first two are compatible with each other; #898 subsumes part of both.

I'd suggest landing #876 and #875 first so `branch-0.4` is unblocked, then deciding between #895 and #898 for `main`. I'm happy to rebase #898 onto whatever lands, or to close it if the generated approach isn't the direction. @the-other-tim-brown @vinishjail97, whichever way you call it works for me — the deadlock costs more than either choice.

*This comment was created with AI assistance.*

**Comment by the-other-tim-brown** [comment]
@slachiewicz I like the #898 approach of using tooling that already exists instead of writing our own.
